import type { GetServerSidePropsContext, NextPage } from "next";
import Head from "next/head";
import styled, { css } from "styled-components";
import { useTheme } from "../contexts/themeContext";
import { IColors } from "../interfaces/IColors";
import { wait } from "../util/wait";

const PageNotFound: NextPage = () => {
  const { colors } = useTheme();

  return (
    <>
      <Head>
        <title>404 | Page Not Found</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container colors={colors}>
        <h1>
          <span className="error-code">404</span>
          <span className="error-message">
            Are you lost baby girl? This page doesn't exist
          </span>
        </h1>
      </Container>
    </>
  );
};

const Container = styled.div<{ colors: IColors }>`
  ${({ colors }) => css`
    width: 100%;
    height: 100vh;
    display: grid;
    place-items: center;
    padding: 20px;
    h1 {
      color: ${colors.foreground1};
      display: flex;
      align-items: center;
      .error-code {
        padding-right: 20px;
        border-right: 1px solid ${colors.foreground1}60;
      }

      .error-message {
        font-size: 14px;
        font-weight: 400;
        margin-left: 20px;
      }
    }
  `}
`;

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
  const pathname = "/" + ctx.req.headers.referer?.split("/").reverse()[0];

  if (pathname) {
    await wait(500);
  }
  return {
    props: { dummy: "dummy" }, // will be passed to the page component as props
  };
}

export default PageNotFound;
