import type { GetServerSidePropsContext, NextPage } from "next";
import Head from "next/head";
import { wait } from "../util/wait";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
  const pathname = "/" + ctx.req.headers.referer?.split("/").reverse()[0];

  if (pathname) {
    await wait(500);
  }
  return {
    props: { dummy: "dummy" }, // will be passed to the page component as props
  };
}

export default Home;
